using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PanelFader : MonoBehaviour
{
    private bool mFaded = false;

    public float Duration = 5f;
    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void OnEnable()
    {
        mFaded = false;

        Fade();
    }

    public void Fade()
    {
        CanvasGroup canvGroup = GetComponent<CanvasGroup>();

        StartCoroutine(DoFade(canvGroup, 0f, 0.95f));
        
        mFaded = !mFaded;
    }

    public IEnumerator DoFade(CanvasGroup canvGroup, float start, float end)
    {
        float counter = 0f;

        while(counter < Duration)
        {
            counter += Time.unscaledDeltaTime;
            Debug.Log(Time.deltaTime.ToString());
            canvGroup.alpha = Mathf.Lerp(start, end, counter / Duration);
            yield return null;
        }
        Debug.Log(Time.deltaTime.ToString());
    }
}
